# Generated by Django 5.0.6 on 2024-07-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoswap_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Pending", "Pending"),
                    ("Exchanged", "Exchanged"),
                ],
                default="Available",
                max_length=10,
            ),
        ),
    ]
